[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.16.0"

[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "2.1.13"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[prune]
  go-tests = true
  unused-packages = true
